// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabApp.Api.Data;

#nullable disable

namespace VocabApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("VocabApp.Api.Models.AiCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromptHash")
                        .IsUnique();

                    b.ToTable("AiCaches");
                });

            modelBuilder.Entity("VocabApp.Api.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetMeanings")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeckId = 1,
                            Definition = "The chance occurrence of a pleasant or useful discovery.",
                            Example = "Finding that quiet bookshop was pure serendipity.",
                            Term = "serendipity"
                        },
                        new
                        {
                            Id = 2,
                            DeckId = 1,
                            Definition = "Able to recover quickly from difficulty or change.",
                            Example = "The resilient team adapted after the setback.",
                            Term = "resilient"
                        },
                        new
                        {
                            Id = 3,
                            DeckId = 1,
                            Definition = "Present or seeming to be present everywhere.",
                            Example = "Smartphones have become ubiquitous in daily life.",
                            Term = "ubiquitous"
                        },
                        new
                        {
                            Id = 4,
                            DeckId = 1,
                            Definition = "Giving much information clearly in very few words.",
                            Example = "Her concise summary captured every important point.",
                            Term = "concise"
                        },
                        new
                        {
                            Id = 5,
                            DeckId = 1,
                            Definition = "The ability to understand and share another person's feelings.",
                            Example = "Good mentors listen with patience and empathy.",
                            Term = "empathy"
                        },
                        new
                        {
                            Id = 6,
                            DeckId = 1,
                            Definition = "Showing careful and persistent effort in work or study.",
                            Example = "A diligent student reviews notes every evening.",
                            Term = "diligent"
                        },
                        new
                        {
                            Id = 7,
                            DeckId = 1,
                            Definition = "Open to more than one interpretation; not clearly defined.",
                            Example = "The contract clause was too ambiguous to enforce.",
                            Term = "ambiguous"
                        },
                        new
                        {
                            Id = 8,
                            DeckId = 1,
                            Definition = "Dealing with problems in a practical, realistic way.",
                            Example = "She took a pragmatic approach and fixed the most urgent issue first.",
                            Term = "pragmatic"
                        },
                        new
                        {
                            Id = 9,
                            DeckId = 1,
                            Definition = "Unwilling or hesitant to do something.",
                            Example = "He was reluctant to speak in front of the class.",
                            Term = "reluctant"
                        },
                        new
                        {
                            Id = 10,
                            DeckId = 1,
                            Definition = "Of considerable importance, size, or worth.",
                            Example = "The project needs a substantial amount of extra time.",
                            Term = "substantial"
                        },
                        new
                        {
                            Id = 11,
                            DeckId = 1,
                            Definition = "Possible and practical to do successfully.",
                            Example = "Building a small prototype first is a feasible plan.",
                            Term = "feasible"
                        },
                        new
                        {
                            Id = 12,
                            DeckId = 1,
                            Definition = "Honest and direct, even when the truth is uncomfortable.",
                            Example = "Please be candid about what still does not work.",
                            Term = "candid"
                        },
                        new
                        {
                            Id = 13,
                            DeckId = 1,
                            Definition = "Continue firmly despite difficulty or opposition.",
                            Example = "If you persist with daily practice, the words will stick.",
                            Term = "persist"
                        },
                        new
                        {
                            Id = 14,
                            DeckId = 1,
                            Definition = "Able to adapt to many different functions or activities.",
                            Example = "English is a versatile skill across many careers.",
                            Term = "versatile"
                        },
                        new
                        {
                            Id = 15,
                            DeckId = 1,
                            Definition = "Showing great attention to detail; very careful and precise.",
                            Example = "Her meticulous notes made revision much easier.",
                            Term = "meticulous"
                        });
                });

            modelBuilder.Entity("VocabApp.Api.Models.CardConfusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfusedWithCardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("LastConfusedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("ConfusedWithCardId");

                    b.HasIndex("UserId", "CardId", "ConfusedWithCardId")
                        .IsUnique();

                    b.ToTable("CardConfusions");
                });

            modelBuilder.Entity("VocabApp.Api.Models.CardProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<float>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.5f);

                    b.Property<DateTime?>("FirstReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LearnedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarkedKnown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("NextReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("CardProgresses", t =>
                        {
                            t.HasCheckConstraint("CK_CardProgress_EaseFactor", "EaseFactor > 0");

                            t.HasCheckConstraint("CK_CardProgress_IncorrectCount", "IncorrectCount >= 0");

                            t.HasCheckConstraint("CK_CardProgress_Interval", "Interval >= 0");

                            t.HasCheckConstraint("CK_CardProgress_Streak", "Streak >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 3,
                            CardId = 3,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 5,
                            CardId = 5,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 6,
                            CardId = 6,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 7,
                            CardId = 7,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 8,
                            CardId = 8,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 9,
                            CardId = 9,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 10,
                            CardId = 10,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 11,
                            CardId = 11,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 12,
                            CardId = 12,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 13,
                            CardId = 13,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 14,
                            CardId = 14,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        },
                        new
                        {
                            Id = 15,
                            CardId = 15,
                            CorrectCount = 0,
                            EaseFactor = 2.5f,
                            IncorrectCount = 0,
                            Interval = 0,
                            MarkedKnown = false,
                            NextReviewDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Streak = 0
                        });
                });

            modelBuilder.Entity("VocabApp.Api.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExampleLevel")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("VocabApp.Api.Models.FreeStudyMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Knows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId", "CardId")
                        .IsUnique();

                    b.ToTable("FreeStudyMarks");
                });

            modelBuilder.Entity("VocabApp.Api.Models.SavedDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TermKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TermKey", "Level", "Definition")
                        .IsUnique();

                    b.ToTable("SavedDefinitions");
                });

            modelBuilder.Entity("VocabApp.Api.Models.SavedExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("B1");

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TermKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TermKey", "DefinitionKey", "Level", "Sentence")
                        .IsUnique();

                    b.ToTable("SavedExamples");
                });

            modelBuilder.Entity("VocabApp.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptHungarianParaphrase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("AiCallCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("AiModel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("google/gemini-3.6-flash");

                    b.Property<bool>("AutomaticAiCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("DailyNewCardGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(20);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("B1");

                    b.Property<bool>("GenerateAlternateDefinitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastStudyDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeechThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(6);

                    b.Property<int>("LongestStudyDayStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("MinimumAnswerSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireAppealReason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ReuseSavedExamples")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("SavedLevelPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("exact");

                    b.Property<int>("StudyDayStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Europe/Budapest");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_DailyNewCardGoal", "DailyNewCardGoal >= 0 AND DailyNewCardGoal <= 100");

                            t.HasCheckConstraint("CK_Users_MinimumAnswerSeconds", "MinimumAnswerSeconds >= 0 AND MinimumAnswerSeconds <= 120");
                        });
                });

            modelBuilder.Entity("VocabApp.Api.Models.UserStudyDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("DayUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IncorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("SecondsStudied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DayUtc")
                        .IsUnique();

                    b.ToTable("UserStudyDays");
                });

            modelBuilder.Entity("VocabApp.Api.Models.Card", b =>
                {
                    b.HasOne("VocabApp.Api.Models.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("VocabApp.Api.Models.CardConfusion", b =>
                {
                    b.HasOne("VocabApp.Api.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.Api.Models.Card", "ConfusedWithCard")
                        .WithMany()
                        .HasForeignKey("ConfusedWithCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("ConfusedWithCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.Api.Models.CardProgress", b =>
                {
                    b.HasOne("VocabApp.Api.Models.Card", "Card")
                        .WithOne("Progress")
                        .HasForeignKey("VocabApp.Api.Models.CardProgress", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("VocabApp.Api.Models.Deck", b =>
                {
                    b.HasOne("VocabApp.Api.Models.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.Api.Models.FreeStudyMark", b =>
                {
                    b.HasOne("VocabApp.Api.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VocabApp.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.Api.Models.UserStudyDay", b =>
                {
                    b.HasOne("VocabApp.Api.Models.User", "User")
                        .WithMany("StudyDays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VocabApp.Api.Models.Card", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("VocabApp.Api.Models.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("VocabApp.Api.Models.User", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("StudyDays");
                });
#pragma warning restore 612, 618
        }
    }
}
